name: Max Parallel
on:
  workflow_dispatch:

jobs:
  approval:
    runs-on: ubuntu-latest
    environment: test
    steps:
      - name: echo
        run: echo 'Approved!'
  deployment:
    needs: approval
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 2
      matrix:
        value: [one, two, three, four, five]
    steps:
      - name: echo
        run: echo ${{ matrix.value }}
